app = "bridgeping"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  DATABASE_PATH = "/app/data/bridgeping.db"
  TZ = "Europe/Amsterdam"

[mounts]
  source = "bridgeping_data"
  destination = "/app/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[metrics]
  port = 9091
  path = "/metrics"